      subroutine writeUHBD(iout,nconvdat,analfile,namlena,icon)
      character*200 analfile
c     Write a UHBD .dat file from convdat
      character*4 ires
      character*8 convdat
      character*200 sfilename
      common /savedat/ mxresdat,maxcondat,ifst(1000),ilst(1000),
     -  nres,iresgen,lsfilename,ires(1000),convdat(7,10000),sfilename
      character*7 libname(3)
      data libname /'Amber  ','CHARMM ','GROMACS'/
      nl=min0(namlena,50)
      write (iout,1000) libname(icon),analfile(1:nl)
      do ia=1,nconvdat
        iatno=ianum(convdat(2,ia),1,4)
        read (convdat(4,ia),*,err=999) ch
        read (convdat(6,ia),*,err=999) eps
        read (convdat(7,ia),*,err=999) sig
        write (iout,2000) convdat(2,ia)(1:4),convdat(1,ia)(1:4),
     -    ch,eps,sig,(sig/2.0)*2.0**(1.0/6.0)
      end do
      return
999   write (6,2001) ia,convdat(4,ia),convdat(6,ia),convdat(7,ia)
      return
1000  format(a,/,'!Generated by Simulaid from ',a,/,
     -  'atom  resi   chrg   epsi   sigm   radi end')
2000  format(a4,2x,a3,6x,5f8.4)
2001  format(' PROGRAM ERROR: invalid data in convdat ia=',i4,
     -  ' convdat4,6,7=',3f9.4)
      end
