      subroutine writegrasp(iout,nconvdat,analfile,namlena)
      character*200 analfile
c     Write a Grasp .crg file from convdat
      character*4 ires
      character*8 convdat
      character*200 sfilename
      common /savedat/ mxresdat,maxcondat,ifst(1000),ilst(1000),
     -  nres,iresgen,lsfilename,ires(1000),convdat(7,10000),sfilename
      nl=min0(namlena,50)
      write (iout,1000) analfile(1:nl)
      write (iout,1001)
      nxa=0
      nxr=0
      do ia=1,nconvdat
        read (convdat(4,ia),*) ch
        write (iout,2000) convdat(2,ia)(1:4),convdat(1,ia)(1:3),ch
        if (convdat(1,ia)(4:4) .ne. ' ') nxr=nxr+1
        if (convdat(2,ia)(5:5) .ne. ' ') nxa=nxa+1
      end do
      if (nxa .gt. 0) write (6,1002) nxa,'atom',4
      if (nxr .gt. 0) write (6,1002) nxr,'residue',3
      return
1000  format('!Generated by Simulaid from ',a)
1001  format('atom__resnumbc_charge_')
1002  format('WARNING: ',i5,1x,a,' names were longer than ',
     -  i1,' characters')
2000  format(a4,2x,a3,6x,f6.3)
      end
